inherit_gem:
  caliber: config/all.yml

plugins: rubocop-sequel

Metrics/AbcSize:
  Exclude:
    - app/aspects/screens/converters/png.rb
    - app/aspects/screens/shoter.rb
Metrics/BlockLength:
  Exclude:
    - config/db/migrate/*
    - slices/authentication/feature.rb
    - slices/authentication/middleware.rb
Metrics/CyclomaticComplexity:
  AllowedMethods:
    - battery_percentage
    - wifi_percentage
Metrics/MethodLength:
  AllowedMethods:
    - battery_percentage
    - wifi_percentage
  Exclude:
    - app/aspects/screens/color_mapper.rb
    - app/aspects/screens/converters/png.rb
    - app/aspects/screens/shoter.rb
    - app/views/helpers.rb
Metrics/ParameterLists:
  Exclude:
    - app/aspects/screens/converters/png.rb
Naming/VariableNumber:
  AllowedPatterns:
    - md5
RSpec/ExampleLength:
  Exclude:
    - "spec/features/**/*"
RSpec/SpecFilePathFormat:
  CustomTransform:
    Terminus: ""
Style/IpAddresses:
  Exclude:
    - spec/**/*
